### ISSUE TITLE
Index script failing

### ISSUE THREAD

**Issue by jglovier** [jglovier/gifs#52]
Not sure I understand why, but the index script is failing.

```shell
|===jglovier===| ~/code/github-jglovier/gifs $ script/build_site_index
/opt/rubies/2.1.5-github1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- builder (LoadError)
	from /opt/rubies/2.1.5-github1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from script/build_site_index:3:in `<main>'
```

cc @parkr for any clues?

**Comment by danilopopeye** [comment]
you're missing the gem `builder`. running `gem install builder` should fix that. :+1:

**Comment by parkr** [comment]
What he said!! ^^

**Comment by parkr** [comment]
Can also set up a gemfile if that helps

**Comment by jglovier** [comment]
:metal: thx!
