### ISSUE TITLE
Scripts won't run after nuking boxen from my system

### ISSUE THREAD

**Issue by jglovier** [jglovier/gifs#58]
Getting the following errors after removing boxen from my system. I think boxen was managing the ruby version, so I installed rbenv instead, but not sure why it's still not working.

Here's the output I'm gettting:

```shell
|===jglovier===| ~/code/github-jglovier/gifs $ script/build_site_index
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- builder (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from script/build_site_index:3:in `<main>'
|===jglovier===| ~/code/github-jglovier/gifs $ script/bootstrap
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.
|===jglovier===| ~/code/github-jglovier/gifs $ which rbenv
/usr/local/bin/rbenv
```

@parkr since you wrote the script, can you give me any tips on how to resolve? :pray:

**Comment by parkr** [comment]
Hey @jglovier! Sorry to hear you're having trouble. Looks like permissions issues. To resolve:

```bash
# First, ensure you have a ruby version installed that you want.
# If you want a GitHub build of Ruby, I have those for ya:
# https://github.com/parkr/ruby-build-github
$ rbenv install YOUR_DESIRED_VERSION
# Now, you have to tell rbenv to use that version.
# Globally is usually easiest, but locally is also possible.
$ rbenv global YOUR_DESIRED_VERSION
$ cd ~/code/github-jglovier/gifs
$ script/bootstrap
$ script/build_site_index
```

That should resolve it. If you already have a Ruby installed with rbenv (check with `rbenv versions`) then you can just run `rbenv local VERSION` or `rbenv global VERSION` and proceed with your scripts as normal. :smiley_cat:

**Comment by jglovier** [comment]
Ahhh there we go. :metal: :tada: Thanks, @parkr!!
